services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crabbish_web
    volumes:
      - ./:/var/www/html
      - ./.Inv_NNJ_php.ini:/usr/local/etc/php/conf.d/zz_inv_nnj_custom_php.ini

    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WP_ENV=${WP_ENV}
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      - UPLOAD_MAX_FILESIZE=64M
      - POST_MAX_SIZE=64M
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:latest
    container_name: crabbish_db
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: crabbish_nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - .:/var/www/html
      - ./certs:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - my-network
    restart: always
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./data:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - my-network

volumes:
  db_data:
    driver: local


networks:
  my-network:
    driver: bridge
